
services:
  app:
    build:
      context: .
      target: ${ENVIRONMENT}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
    develop:
      watch:
        - action: sync
          path: ./bookmodeling
          target: ./app/bookmodeling
        - action: sync
          path: ./tests
          target: /app/tests
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${HOST_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5